package moblin

import "time"

// --- Messages to Streamer ---

// ResultPayload maps to the Swift RemoteControlResult enum.
// Because Swift Codable serializes enums without raw values as keyed objects,
// only one of these fields will be non-nil.
type ResultPayload struct {
	Ok                *struct{} `json:"ok,omitempty"`                // Operation succeeded
	WrongPassword     *struct{} `json:"wrongPassword,omitempty"`     // Authentication failed
	UnknownRequest    *struct{} `json:"unknownRequest,omitempty"`    // Command not recognized by Moblin
	NotIdentified     *struct{} `json:"notIdentified,omitempty"`     // Command sent before authentication
	AlreadyIdentified *struct{} `json:"alreadyIdentified,omitempty"` // Duplicate identify payload
	Error             *struct{} `json:"error,omitempty"`             // General operational failure
}

// MessageToStreamer is the envelope for all data sent from the Assistant to the Moblin app.
type MessageToStreamer struct {
	Hello      *HelloData      `json:"hello,omitempty"`      // Initial handshake from server containing challenge
	Identified *IdentifiedData `json:"identified,omitempty"` // Server's response to Moblin's identify payload
	Request    *RequestPayload `json:"request,omitempty"`    // RPC command (e.g., start recording, zoom)
	Pong       *struct{}       `json:"pong,omitempty"`       // Keepalive response
}

// HelloData initiates the double-SHA256 authentication flow.
type HelloData struct {
	ApiVersion     string         `json:"apiVersion"`     // Currently "0.1"
	Authentication Authentication `json:"authentication"` // Contains the generated challenge/salt
}

type Authentication struct {
	Challenge string `json:"challenge"` // Random string generated by Assistant
	Salt      string `json:"salt"`      // Random string generated by Assistant
}

// IdentifiedData confirms or denies the Moblin app's connection attempt.
type IdentifiedData struct {
	Result ResultPayload `json:"result"`
}

// RequestPayload wraps a specific command with an incrementing ID to track synchronous responses.
type RequestPayload struct {
	ID   uint64  `json:"id"`
	Data Request `json:"data"`
}

// --- Request Core ---

// Request models all cases of the Swift RemoteControlRequest enum.
// These are commands the Assistant sends to control the Moblin stream.
type Request struct {
	GetStatus                         *struct{}               `json:"getStatus,omitempty"`                         // Polls for current battery, thermal, and UI element status
	GetSettings                       *struct{}               `json:"getSettings,omitempty"`                       // Fetches configured scenes, mics, and bitrate presets
	SetRecord                         *BoolReq                `json:"setRecord,omitempty"`                         // Toggles local device recording
	SetStream                         *BoolReq                `json:"setStream,omitempty"`                         // Toggles RTMP/SRT streaming
	SetZoom                           *FloatReq               `json:"setZoom,omitempty"`                           // Sets raw camera zoom level (e.g., 1.0, 2.0)
	SetZoomPreset                     *UUIDReq                `json:"setZoomPreset,omitempty"`                     // Switches to a predefined zoom preset ID
	SetMute                           *BoolReq                `json:"setMute,omitempty"`                           // Toggles microphone mute
	SetTorch                          *BoolReq                `json:"setTorch,omitempty"`                          // Toggles the device flashlight
	SetDebugLogging                   *BoolReq                `json:"setDebugLogging,omitempty"`                   // Toggles verbose internal logging
	SetScene                          *UUIDReq                `json:"setScene,omitempty"`                          // Switches to a specific Scene ID
	SetAutoSceneSwitcher              *UUIDReq                `json:"setAutoSceneSwitcher,omitempty"`              // Enables/disables automatic scene switching logic
	SetBitratePreset                  *UUIDReq                `json:"setBitratePreset,omitempty"`                  // Switches to a specific Bitrate Preset ID
	SetMic                            *StringIDReq            `json:"setMic,omitempty"`                            // Switches the active microphone hardware
	SetSrtConnectionPriority          *SetSrtPriorityReq      `json:"setSrtConnectionPriority,omitempty"`          // Modifies cellular/WiFi bonding priority for SRT connections
	SetSrtConnectionPrioritiesEnabled *EnabledReq             `json:"setSrtConnectionPrioritiesEnabled,omitempty"` // Toggles SRT connection bonding logic
	ReloadBrowserWidgets              *struct{}               `json:"reloadBrowserWidgets,omitempty"`              // Forces a refresh of all web overlays
	TwitchEventSubNotification        *MessageReq             `json:"twitchEventSubNotification,omitempty"`        // Proxies a Twitch EventSub notification to the streamer
	StartPreview                      *struct{}               `json:"startPreview,omitempty"`                      // Commands Moblin to start sending JPEG preview frames
	StopPreview                       *struct{}               `json:"stopPreview,omitempty"`                       // Commands Moblin to stop sending preview frames
	ChatMessages                      *ChatMessagesReq        `json:"chatMessages,omitempty"`                      // Proxies chat messages (e.g., from Twitch/YouTube) into the app
	SetRemoteSceneSettings            *RemoteSceneSettingsReq `json:"setRemoteSceneSettings,omitempty"`            // Overrides remote scene configurations
	SetRemoteSceneData                *RemoteSceneDataReq     `json:"setRemoteSceneData,omitempty"`                // Pushes real-time IRL telemetry (speed, altitude, HR) to widgets
	InstantReplay                     *struct{}               `json:"instantReplay,omitempty"`                     // Triggers an instant replay buffer
	SaveReplay                        *struct{}               `json:"saveReplay,omitempty"`                        // Saves the current replay buffer to disk
	StartStatus                       *StartStatusReq         `json:"startStatus,omitempty"`                       // Initiates a continuous stream of `Event.Status` payloads at the given interval
	StopStatus                        *struct{}               `json:"stopStatus,omitempty"`                        // Stops the continuous status stream
	GetScoreboardSports               *struct{}               `json:"getScoreboardSports,omitempty"`               // Fetches available sports logic for the scoreboard widget
	SetScoreboardSport                *SportIDReq             `json:"setScoreboardSport,omitempty"`                // Sets the active sport logic
	UpdateScoreboard                  *UpdateScoreboardReq    `json:"updateScoreboard,omitempty"`                  // Updates the teams, scores, and clocks on the scoreboard overlay
	ToggleScoreboardClock             *struct{}               `json:"toggleScoreboardClock,omitempty"`             // Pauses/resumes the scoreboard timer
	SetScoreboardDuration             *MinutesReq             `json:"setScoreboardDuration,omitempty"`             // Sets the timer duration
	SetScoreboardClock                *TimeReq                `json:"setScoreboardClock,omitempty"`                // Hard-sets the clock string (e.g., "12:00")
	Whip                              *WhipReq                `json:"whip,omitempty"`                              // WebRTC HTTP Ingestion Protocol signaling
	SetFilter                         *SetFilterReq           `json:"setFilter,omitempty"`                         // Enables/disables specific video filters (e.g., Pixellate, BlurFaces)
}

type BoolReq struct {
	On bool `json:"on"`
}
type FloatReq struct {
	X float32 `json:"x"`
}
type UUIDReq struct {
	ID string `json:"id"` // Moblin UUIDs serialize to standard uppercase dashed strings
}
type StringIDReq struct {
	ID string `json:"id"`
}
type MessageReq struct {
	Message string `json:"message"`
}
type EnabledReq struct {
	Enabled bool `json:"enabled"`
}
type SportIDReq struct {
	SportID string `json:"sportId"` // e.g., "football"
}
type MinutesReq struct {
	Minutes int `json:"minutes"`
}
type TimeReq struct {
	Time string `json:"time"`
}

type SetSrtPriorityReq struct {
	ID       string `json:"id"`
	Priority int    `json:"priority"` // Lower number = higher priority for bonding
	Enabled  bool   `json:"enabled"`
}

type ChatMessagesReq struct {
	History  bool          `json:"history"` // True if injecting backlog history, false for real-time
	Messages []ChatMessage `json:"messages"`
}

type RemoteSceneSettingsReq struct {
	Data RemoteSceneSettings `json:"data"`
}
type RemoteSceneDataReq struct {
	Data RemoteSceneData `json:"data"`
}
type UpdateScoreboardReq struct {
	Config ScoreboardMatchConfig `json:"config"`
}

type StartStatusFilter struct {
	TopRight bool `json:"topRight"` // True explicitly enables TopRight UI telemetry
}
type StartStatusReq struct {
	Interval int               `json:"interval"` // Frequency in seconds to push Status payload
	Filter   StartStatusFilter `json:"filter"`
}

type WhipReq struct {
	URL     string       `json:"url"`
	Method  string       `json:"method"`
	Headers []HttpHeader `json:"headers"`
	Body    []byte       `json:"body"`
}

type SetFilterReq struct {
	Filter string `json:"filter"` // Maps to RemoteControlFilter enum (e.g., "pixellate", "blurFaces")
	On     bool   `json:"on"`
}

// --- Response Wrappers ---

// ResponseData holds the synchronous return payloads triggered by Request commands.
type ResponseData struct {
	GetStatus           *StatusPayload   `json:"getStatus,omitempty"`
	GetSettings         *SettingsPayload `json:"getSettings,omitempty"`
	GetScoreboardSports *SportsPayload   `json:"getScoreboardSports,omitempty"`
	Whip                *WhipPayload     `json:"whip,omitempty"`
}

type SettingsPayload struct {
	Data Settings `json:"data"`
}
type SportsPayload struct {
	Names []string `json:"names"`
}
type WhipPayload struct {
	Status  int          `json:"status"`
	Headers []HttpHeader `json:"headers"`
	Body    []byte       `json:"body"`
}

// --- Core Models ---

// Settings outlines the streaming configuration currently loaded into Moblin.
type Settings struct {
	Scenes             []Scene             `json:"scenes"` // Available scene templates
	AutoSceneSwitchers []AutoSceneSwitcher `json:"autoSceneSwitchers,omitempty"`
	BitratePresets     []BitratePreset     `json:"bitratePresets"` // Target streaming bitrates
	Mics               []Mic               `json:"mics"`           // Available microphone hardware routes
	Srt                SrtSettings         `json:"srt"`            // Secure Reliable Transport bonding config
}

type Scene struct {
	ID   string `json:"id"` // UUID string
	Name string `json:"name"`
}

type AutoSceneSwitcher struct {
	ID   string `json:"id"` // UUID string
	Name string `json:"name"`
}

type BitratePreset struct {
	ID      string `json:"id"`      // UUID string
	Bitrate uint32 `json:"bitrate"` // Value in bps (e.g., 5000000 for 5Mbps)
}

type Mic struct {
	ID   string `json:"id"`   // Internal iOS route ID
	Name string `json:"name"` // Human-readable name (e.g., "Back Wide dual")
}

type SrtSettings struct {
	ConnectionPrioritiesEnabled bool                    `json:"connectionPrioritiesEnabled"`
	ConnectionPriorities        []SrtConnectionPriority `json:"connectionPriorities"`
}

type SrtConnectionPriority struct {
	ID       string `json:"id"`
	Name     string `json:"name"`     // Interface name (e.g., "Cellular", "WiFi")
	Priority int    `json:"priority"` // Ordering for SRTLA bonding
	Enabled  bool   `json:"enabled"`
}

type HttpHeader struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// ChatMessage represents a single proxied chat payload intended for Moblin's chat widget.
type ChatMessage struct {
	ID           int               `json:"id"`
	Platform     string            `json:"platform"` // e.g., "twitch", "youtube"
	MessageID    *string           `json:"messageId,omitempty"`
	DisplayName  *string           `json:"displayName,omitempty"`
	User         *string           `json:"user,omitempty"`
	UserID       *string           `json:"userId,omitempty"`
	UserColor    *RgbColor         `json:"userColor,omitempty"`
	UserBadges   []string          `json:"userBadges"` // URLs pointing to badge icon images
	Segments     []ChatPostSegment `json:"segments"`   // Sliced array of text/emote blocks
	Timestamp    string            `json:"timestamp"`  // String formatted time
	IsAction     bool              `json:"isAction"`
	IsModerator  bool              `json:"isModerator"`
	IsSubscriber bool              `json:"isSubscriber"`
	IsOwner      bool              `json:"isOwner"`
	Bits         *string           `json:"bits,omitempty"`
}

type RgbColor struct {
	R int `json:"r"`
	G int `json:"g"`
	B int `json:"b"`
}

type ChatPostSegment struct {
	Text *string `json:"text,omitempty"`
	URL  *string `json:"url,omitempty"`
}

// --- Scoreboard Models ---

// ScoreboardMatchConfig dictates the layout and state of Moblin's custom sports scoreboard overlay.
type ScoreboardMatchConfig struct {
	SportID  string                       `json:"sportId"` // Determines period logic (e.g., "football", "soccer")
	Layout   string                       `json:"layout"`  // UI template to render
	Team1    ScoreboardTeam               `json:"team1"`
	Team2    ScoreboardTeam               `json:"team2"`
	Global   GlobalStats                  `json:"global"`
	Controls map[string]ScoreboardControl `json:"controls"`
}

type ScoreboardTeam struct {
	Name                string  `json:"name"`
	BgColor             string  `json:"bgColor"` // Hex string
	TextColor           string  `json:"textColor"`
	Possession          bool    `json:"possession"`
	PrimaryScore        string  `json:"primaryScore"`
	SecondaryScore      string  `json:"secondaryScore"`
	SecondaryScoreLabel *string `json:"secondaryScoreLabel,omitempty"`
	SecondaryScore1     *string `json:"secondaryScore1,omitempty"`
	SecondaryScore2     *string `json:"secondaryScore2,omitempty"`
	SecondaryScore3     *string `json:"secondaryScore3,omitempty"`
	SecondaryScore4     *string `json:"secondaryScore4,omitempty"`
	SecondaryScore5     *string `json:"secondaryScore5,omitempty"`
	Stat1               string  `json:"stat1"`
	Stat1Label          string  `json:"stat1Label"`
	Stat2               string  `json:"stat2"`
	Stat2Label          string  `json:"stat2Label"`
	Stat3               string  `json:"stat3"`
	Stat3Label          string  `json:"stat3Label"`
	Stat4               string  `json:"stat4"`
	Stat4Label          string  `json:"stat4Label"`
}

type GlobalStats struct {
	Title                       string  `json:"title"`
	Timer                       string  `json:"timer"`              // The active clock string
	TimerDirection              string  `json:"timerDirection"`     // "up" or "down"
	Duration                    *int    `json:"duration,omitempty"` // Total minutes per period
	Period                      string  `json:"period"`             // e.g., "1", "2", "Half"
	PeriodLabel                 string  `json:"periodLabel"`        // e.g., "Period", "Quarter"
	InfoBoxText                 string  `json:"infoBoxText"`
	PrimaryScoreResetOnPeriod   *bool   `json:"primaryScoreResetOnPeriod,omitempty"`
	SecondaryScoreResetOnPeriod *bool   `json:"secondaryScoreResetOnPeriod,omitempty"`
	ChangePossessionOnScore     *bool   `json:"changePossessionOnScore,omitempty"`
	ScoringMode                 *string `json:"scoringMode,omitempty"`
	MinSetScore                 *int    `json:"minSetScore,omitempty"`
	MaxSetScore                 *int    `json:"maxSetScore,omitempty"`
	ShowTitle                   *bool   `json:"showTitle,omitempty"`
	ShowStats                   *bool   `json:"showStats,omitempty"`
	ShowMoreStats               *bool   `json:"showMoreStats,omitempty"`
}

type ScoreboardControl struct {
	Type        string   `json:"type"`
	Label       string   `json:"label"`
	Options     []string `json:"options,omitempty"`
	PeriodReset *bool    `json:"periodReset,omitempty"`
}

// --- Remote Scene Models ---

type RemoteSceneSettings struct {
	Scenes          []RemoteSceneSettingsScene  `json:"scenes"`
	Widgets         []RemoteSceneSettingsWidget `json:"widgets"`
	SelectedSceneID *string                     `json:"selectedSceneId,omitempty"`
}

type RemoteSceneSettingsScene struct {
	ID      string                           `json:"id"`
	Widgets []RemoteSceneSettingsSceneWidget `json:"widgets"`
}

type RemoteSceneSettingsSceneWidget struct {
	ID   string  `json:"id"`
	X    float64 `json:"x"`
	Y    float64 `json:"y"`
	Size float64 `json:"size"`
}

// RemoteSceneSettingsWidget defines overlay configuration. The Type field maps Swift enums
// to a JSON object containing specific widget parameters (e.g., Browser, Text, Map).
type RemoteSceneSettingsWidget struct {
	ID      string                 `json:"id"`
	Enabled bool                   `json:"enabled"`
	Type    map[string]interface{} `json:"type"`
}

// RemoteSceneData allows external sensors (like Apple Watches or IoT devices)
// to push live telemetry into Moblin's text overlays.
type RemoteSceneData struct {
	TextStats *TextStats `json:"textStats,omitempty"`
	Location  *Location  `json:"location,omitempty"`
}

// TextStats contains extensive variables intended to be templated into Moblin text widgets
// during high-motion IRL streaming (e.g., cycling, driving, running).
type TextStats struct {
	Bitrate              string                 `json:"bitrate"`
	BitrateAndTotal      string                 `json:"bitrateAndTotal"`
	Resolution           *string                `json:"resolution,omitempty"`
	Fps                  *int                   `json:"fps,omitempty"`
	Date                 time.Time              `json:"date"`
	DebugOverlayLines    []string               `json:"debugOverlayLines"`
	Speed                string                 `json:"speed"` // GPS calculated speed
	AverageSpeed         string                 `json:"averageSpeed"`
	Altitude             string                 `json:"altitude"`
	Distance             string                 `json:"distance"`
	Slope                string                 `json:"slope"`
	Conditions           *string                `json:"conditions,omitempty"` // Weather conditions
	Temperature          *float64               `json:"temperature,omitempty"`
	FeelsLikeTemperature *float64               `json:"feelsLikeTemperature,omitempty"`
	WindSpeed            *float64               `json:"windSpeed,omitempty"`
	WindGust             *float64               `json:"windGust,omitempty"`
	Country              *string                `json:"country,omitempty"`
	CountryFlag          *string                `json:"countryFlag,omitempty"`
	State                *string                `json:"state,omitempty"`
	City                 *string                `json:"city,omitempty"`
	Muted                bool                   `json:"muted"`
	HeartRates           map[string]*int        `json:"heartRates"` // Extracted from Bluetooth/HealthKit
	ActiveEnergyBurned   *int                   `json:"activeEnergyBurned,omitempty"`
	WorkoutDistance      *int                   `json:"workoutDistance,omitempty"`
	Power                *int                   `json:"power,omitempty"` // Cycling power meter watts
	StepCount            *int                   `json:"stepCount,omitempty"`
	TeslaBatteryLevel    string                 `json:"teslaBatteryLevel"` // EV telemetry integration
	TeslaDrive           string                 `json:"teslaDrive"`
	TeslaMedia           string                 `json:"teslaMedia"`
	CyclingPower         string                 `json:"cyclingPower"`
	CyclingCadence       string                 `json:"cyclingCadence"`
	RunningMetrics       map[string]interface{} `json:"runningMetrics"` // Pace, cadence, etc.
	BrowserTitle         string                 `json:"browserTitle"`
	GForce               interface{}            `json:"gForce,omitempty"`
}

type Location struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type BoolData struct {
	On bool `json:"on"`
}

type FloatData struct {
	X float32 `json:"x"`
}

// --- Messages to Assistant ---

// MessageToAssistant is the envelope for all data sent from Moblin back to the server.
type MessageToAssistant struct {
	Identify *IdentifyData `json:"identify,omitempty"` // Initial authentication payload
	Event    *EventWrapper `json:"event,omitempty"`    // Unsolicited state mutations or interval statuses
	Response *Response     `json:"response,omitempty"` // Synchronous replies to Request payloads
	Preview  *PreviewData  `json:"preview,omitempty"`  // Raw camera frame bytes
	Ping     *struct{}     `json:"ping,omitempty"`     // Keepalive packet
}

// EventWrapper unwraps the nested structure caused by Swift's enum serialization `case event(data: ...)`.
type EventWrapper struct {
	Data EventPayload `json:"data"`
}

type IdentifyData struct {
	StreamerId     *string `json:"streamerId"`
	Authentication string  `json:"authentication"` // The resulting SHA256 double-hash from the challenge
}

type EventPayload struct {
	State      *StateEvent  `json:"state,omitempty"`
	Log        *LogEvent    `json:"log,omitempty"`
	Status     *StatusEvent `json:"status,omitempty"`
	Scoreboard interface{}  `json:"scoreboard,omitempty"`
}

type LogEvent struct {
	Entry string `json:"entry"` // Internal debug string from the iOS console
}

type StateEvent struct {
	Data StreamerState `json:"data"`
}

type StatusEvent struct {
	Data StatusPayload `json:"data"`
}

type Response struct {
	ID     uint64        `json:"id"`
	Result ResultPayload `json:"result"`
	Data   *ResponseData `json:"data"`
}

type PreviewData struct {
	Preview []byte `json:"preview"` // Base64 JPEG frame. Handled automatically by encoding/json
}

// --- Core Data Models ---

// StreamerState represents the core operational state of the Moblin device.
// IMPORTANT: Moblin pushes partial updates (deltas) of this struct.
// You must merge incoming payloads, as omitted fields do not imply nullification.
type StreamerState struct {
	Scene             *string                 `json:"scene,omitempty"` // UUID string
	AutoSceneSwitcher *AutoSceneSwitcherState `json:"autoSceneSwitcher,omitempty"`
	Mic               *string                 `json:"mic,omitempty"`
	Bitrate           *string                 `json:"bitrate,omitempty"` // UUID string
	Zoom              *float32                `json:"zoom,omitempty"`
	ZoomPresets       []ZoomPreset            `json:"zoomPresets,omitempty"`
	ZoomPreset        *string                 `json:"zoomPreset,omitempty"` // UUID string
	DebugLogging      *bool                   `json:"debugLogging,omitempty"`
	Streaming         *bool                   `json:"streaming,omitempty"`
	Recording         *bool                   `json:"recording,omitempty"`
	Muted             *bool                   `json:"muted,omitempty"`
	TorchOn           *bool                   `json:"torchOn,omitempty"`
	BatteryCharging   *bool                   `json:"batteryCharging,omitempty"`
	Filters           map[string]bool         `json:"filters,omitempty"`
}

type AutoSceneSwitcherState struct {
	ID *string `json:"id,omitempty"` // UUID string
}

type ZoomPreset struct {
	ID   string `json:"id"` // UUID string
	Name string `json:"name"`
}

// StatusPayload contains real-time hardware metrics. Pushed continuously only if
// a StartStatus interval was requested, or returned synchronously via GetStatus.
type StatusPayload struct {
	General  *StatusGeneral  `json:"general,omitempty"`  // Device-level hardware states (battery, thermals, toggles)
	TopLeft  *StatusTopLeft  `json:"topLeft,omitempty"`  // Maps to Top-Left UI elements (Stream health, camera, viewers)
	TopRight *StatusTopRight `json:"topRight,omitempty"` // Maps to Top-Right UI elements (Audio dB levels, SRTLA metrics)
}

// StatusGeneral represents critical device health parameters.
type StatusGeneral struct {
	BatteryCharging *bool   `json:"batteryCharging,omitempty"`
	BatteryLevel    *int    `json:"batteryLevel,omitempty"` // Integer percentage (0-100)
	Flame           *string `json:"flame,omitempty"`        // Maps to iOS ProcessInfo.ThermalState. "White"=Fair, "Yellow"=Serious, "Red"=Critical
	WiFiSsid        *string `json:"wiFiSsid,omitempty"`     // Connected network name
	IsLive          *bool   `json:"isLive,omitempty"`       // Broadcast active
	IsRecording     *bool   `json:"isRecording,omitempty"`  // Local record active
	IsMuted         *bool   `json:"isMuted,omitempty"`      // Audio silenced
}

// StatusItem represents a localized UI metric string and its health status
// directly reflecting the visual badges in the Moblin app.
type StatusItem struct {
	Message string `json:"message"` // The formatted text displayed in the UI (e.g., "3.5 Mbps", "1080p • 60 fps")
	Ok      bool   `json:"ok"`      // True if the metric is in a healthy state, false if warning/critical
}

// StatusTopLeft contains metrics displayed in the top-left area of the Moblin UI.
type StatusTopLeft struct {
	Stream  *StatusItem `json:"stream,omitempty"`  // Broadcast destination status and duration
	Camera  *StatusItem `json:"camera,omitempty"`  // Active camera resolution and framerate
	Mic     *StatusItem `json:"mic,omitempty"`     // Active microphone hardware name
	Zoom    *StatusItem `json:"zoom,omitempty"`    // Current optical/digital zoom multiplier
	Obs     *StatusItem `json:"obs,omitempty"`     // OBS WebSocket remote connection status
	Events  *StatusItem `json:"events,omitempty"`  // Recent stream events or alerts (follows/subs)
	Chat    *StatusItem `json:"chat,omitempty"`    // Twitch/YouTube chat connection health
	Viewers *StatusItem `json:"viewers,omitempty"` // Current concurrent viewer count
}

// StatusTopRight contains metrics displayed in the top-right area of the Moblin UI.
type StatusTopRight struct {
	AudioInfo      *AudioInfo  `json:"audioInfo,omitempty"`      // Raw audio channel and level data (StatusTopRightAudioInfo)
	AudioLevel     *StatusItem `json:"audioLevel,omitempty"`     // Formatted audio dB level string (e.g., "-5 dB")
	RtmpServer     *StatusItem `json:"rtmpServer,omitempty"`     // Internal RTMP server connection health
	RemoteControl  *StatusItem `json:"remoteControl,omitempty"`  // Remote control assistant connection status
	GameController *StatusItem `json:"gameController,omitempty"` // Connected bluetooth game controller status
	Bitrate        *StatusItem `json:"bitrate,omitempty"`        // Current outbound streaming bitrate
	Uptime         *StatusItem `json:"uptime,omitempty"`         // System or application uptime
	Location       *StatusItem `json:"location,omitempty"`       // GPS location coordinates or speed data
	Srtla          *StatusItem `json:"srtla,omitempty"`          // SRTLA bonded connection health and dropped packets
	SrtlaRtts      *StatusItem `json:"srtlaRtts,omitempty"`      // SRTLA Round Trip Time latencies
	Recording      *StatusItem `json:"recording,omitempty"`      // Local file recording status and duration
	Replay         *StatusItem `json:"replay,omitempty"`         // Instant replay buffer state
	BrowserWidgets *StatusItem `json:"browserWidgets,omitempty"` // Health of interactive browser overlays
	Moblink        *StatusItem `json:"moblink,omitempty"`        // Moblink cellular bonding status
	DjiDevices     *StatusItem `json:"djiDevices,omitempty"`     // Connected DJI drone/gimbal hardware status
	SystemMonitor  *StatusItem `json:"systemMonitor,omitempty"`  // CPU, memory, and thermal system metrics
}

// AudioInfo replaces the interface{} in StatusTopRight
type AudioInfo struct {
	AudioLevel            AudioLevel `json:"audioLevel"`
	NumberOfAudioChannels int        `json:"numberOfAudioChannels"`
}

// AudioLevel maps to RemoteControlStatusTopRightAudioLevel.
// Swift Codable enums serialize as single-key objects, which maps cleanly to pointers in Go.
type AudioLevel struct {
	Value   *float32  `json:"value,omitempty"`
	Muted   *struct{} `json:"muted,omitempty"`
	Unknown *struct{} `json:"unknown,omitempty"`
}
